Fix fatal error when accessing non exist user value
humanmade/hm-gtm pull request #28
Opened 2021-02-02 12:00 UTC by ivankristianto

This PR fixed fatal error thrown when using `get_user_by()` function which could return false.

Error log:
```
[25-Jan-2021 09:53:34 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get() on boolean in /usr/src/app/vendor/humanmade/hm-gtm/inc/template-tags.php:150
Stack trace:
#0 /usr/src/app/vendor/humanmade/hm-gtm/inc/namespace.php(86): get_gtm_data_layer()
#1 /usr/src/app/wordpress/wp-includes/class-wp-hook.php(285): HM\GTM\output_tag()
#2 /usr/src/app/wordpress/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#3 /usr/src/app/wordpress/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /usr/src/app/wordpress/wp-includes/general-template.php(2884): do_action('wp_head')
#5 /usr/src/app/content/themes/standard-chartered-non-retail/header.php(20): wp_head()
#6 /usr/src/app/wordpress/wp-includes/template.php(723): require_once('/usr/src/app/co...')
#7 /usr/src/app/wordpress/wp-includes/template.php(672): load_template('/usr/src/app/co...', true)
#8 /usr/src/app/wordpress/wp-includes/general-template.php(41): locate_template(Array, true)
#9 /usr/src/app/content/themes/standard-chartered-non-retail/singular.php(8): get_header()
#10 /usr/src/app/wordpress/wp-includes/template-loader.php(106): include('/usr/src/app/co...')
#11 /usr/src/app/wordpress/wp-blog-header.php(19): require_once('/usr/src/app/wo...')
#12 /usr/src/app/index.php(21): require('/usr/src/app/wo...')
#13 {main}
thrown in /usr/src/app/vendor/humanmade/hm-gtm/inc/template-tags.php on line 150
```

2021-02-02 16:24 UTC, roborourke requested changes
Can you remove the whitespace changes? Our coding standards don't require aligning assignment operators. It just creates unnecessary code churn and increases the likelihood that patches won't apply cleanly in situations where multiple people might be working on the same code / files.

2021-02-02 16:24 UTC, roborourke commented on inc/template-tags.php
> +				$data['post']['author_ID']   = $user->ID;
```suggestion
				$data['post']['author_ID'] = $user->ID;
```

2021-02-03 08:33 UTC, ivankristianto commented
Thanks @roborourke 
I did revert and remove the whitespaces as per your feedback.

2021-02-03 09:50 UTC, roborourke approved these changes

2021-02-03 09:50 UTC, merged